---
- name: docker-playbook
  hosts: docker-servers
  become: true

  tasks:
    - name: Deploy Docker Container
      docker_container:
        name: amolkadwe/ansible-flask-app:latest
        image: democontainer:v1.0
        state: started
        ports:
          - "5000:5000"
