---
- name: docker-playbook
  hosts: Docker-Servers
  become: true

  tasks:
    - name: Stop the running container
      docker_container:
        name: ansible-flask-app
        state: stopped
      ignore_errors: yes
      
    - name: Pull the latest Docker image
      docker_image:
        name: amolkadwe/ansible-flask-app:latest
        source: pull
      
    - name: Deploy Docker Container
      docker_container:
        name: ansible-flask-app
        image: amolkadwe/ansible-flask-app:latest
        state: started
        ports:
          - "5000:5000"
