apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # The port you want to expose externally
      targetPort: 5000 # The port your Flask app is listening on inside the container
  type: LoadBalancer # Change this to the appropriate service type based on your setup
